### ISSUE TITLE
Exceptions in Analyzer

### ISSUE THREAD

**Issue by WalkerCodeRanger** [WalkerCodeRanger/ExhaustiveMatching#24]
The analyzer still throws exceptions sometimes which show up as warnings in VS. I think it is because of invalid code, but I'm not sure. Things to try:

* Unknown Type in Case Clause
* Unknown Type in Case Class List

**Comment by WalkerCodeRanger** [comment]
Here is one of the errors:
```
Warning	AD0001	Analyzer 'ExhaustiveMatching.Analyzer.ExhaustiveMatchAnalyzer' threw an exception of type 'System.ArgumentException' with message 'Syntax node is not within syntax tree'.	
```

**Comment by WalkerCodeRanger** [comment]
New codebase gives full stacktrace:
```console
Uncaught exception in analyzer: System.ArgumentException: Syntax node is not within syntax tree
    at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.CheckSyntaxNode(CSharpSyntaxNode syntax)
    at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetTypeInfo(ExpressionSyntax expression, CancellationToken cancellationToken)
    at Microsoft.CodeAnalysis.CSharp.CSharpExtensions.GetTypeInfo(SemanticModel semanticModel, ExpressionSyntax expression, CancellationToken cancellationToken)
    at ExhaustiveMatching.Analyzer.TypeDeclarationAnalyzer.AllMemberTypesMustBeDirectSubtypes(SyntaxNodeAnalysisContext context, TypeDeclarationSyntax typeDeclaration, ITypeSymbol typeSymbol, INamedTypeSymbol closedAttribute)
    at ExhaustiveMatching.Analyzer.TypeDeclarationAnalyzer.Analyze(SyntaxNodeAnalysisContext context, TypeDeclarationSyntax typeDeclaration)
    at ExhaustiveMatching.Analyzer.ExhaustiveMatchAnalyzer.AnalyzeTypeDeclaration(SyntaxNodeAnalysisContext context)
```
